//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTeam
    {
        public int TeamID { get; set; }
        public System.DateTime UserID { get; set; }
        public bool IsManager { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
